### ISSUE TITLE
MonoKickstart for Windows

### ISSUE THREAD

**Issue by LennardF1989** [flibitijibibo/MonoKickstart#6]
I'm getting really sick of people having issues because of broken .NET installations, or explaining yet again that having 4.6.2 is not the same as having 3.5/4.0/etc.

Just a wild idea, but would compiling MonoKickstart as a Windows application do anything, so I have a consistent environment for all platforms?

**Comment by flibitijibibo** [comment]
It’s been done before but I dunno if it’s any good. You could always ship the redist with it, along with the other redists:

https://github.com/FNA-XNA/FNA/wiki/3:-Distributing-FNA-Games#windows

That’s what we did before stores automated it, at least. I think there are little tricks you can do to detect the redists too (registry stuff?), but again I’ve never tried it.

**Comment by mrhelmut** [comment]
Mono on Windows really isn't on par with its linux/unix counterpart. My attempts haven't been quite reliable, I wouldn't recommend it.

I would suggest detecting the required .Net version through a registry key check, and prompt the player with a link to download it if it isn't installed.

For .Net 4.5, check this key: ```HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full```

Reference: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by flibitijibibo** [comment]
Closing as WONTFIX - in addition to the registry detection (which I believe Microsoft themselves recommend!), my guess is CoreCLR will get priority over Mono for embedded .NET on Windows. I don't think we can maintain this ourselves, even though I really don't like CoreCLR...
