### ISSUE TITLE
Terraria 1.4

### ISSUE THREAD

**Issue by StephenLynx** [flibitijibibo/MonoKickstart#8]
I've tried using this on terraria and I get this error when trying to run:

Corlib not in sync with this runtime: expected corlib version 149, found 36.

**Comment by flibitijibibo** [comment]
You did not update all the files. It may be better to wait until a proper patch is made by a developer (or modder).

**Comment by StephenLynx** [comment]
I just copied all the files  from the precompiled directory and pasted over the ones I had. Was there anything else I should've done or those files just don't work with 1.4?

**Comment by flibitijibibo** [comment]
The kick file needs to be renamed to the main assembly name. Again, you probably will want someone who knows what they’re doing to put this together safely for you, throwing arbitrary files around is not a good idea.

**Comment by StephenLynx** [comment]
I should've rtfm'd tbh. Anyway, it worked and it improved performance by a reasonable margin.

**Comment by StephenLynx** [comment]
Now, there are 2 quirks that I'm observing:

1: the game won't launch if I use setsid steam -no-browser

2: the game takes a while to actually stop running when I exit.
